---
micronaut:
    application:
        name: maps-service
    server:
        port: -1

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
